# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file into the container at /app
COPY app/requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Install ffmpeg
RUN apt-get update && apt-get install -y ffmpeg

# Copy the current directory contents into the container at /app
COPY . /app

# Define environment variable for the token
ENV DISCORD_TOKEN=""

# Run main.py when the container launches
ENTRYPOINT ["sh", "-c", "python app/main.py --token $DISCORD_TOKEN"]

